name: security
on: [push, pull_request]
jobs:
  gokart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v2.1.3
        with:
          go-version: 1.17
      - name: Install gokart
        run: go install github.com/praetorian-inc/gokart@latest
      - name: Run gokart
        run: gokart scan --exitCode
