name: security
on: [push, pull_request]
jobs:
  gokart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set up Go
        uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 # v2.1.3
        with:
          go-version: 1.17
      - name: Install gokart
        run: go install github.com/praetorian-inc/gokart@latest
      - name: Run gokart
        run: gokart scan --exitCode
